# coding: utf-8

"""
    Aspose.Email for Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ListFoldersResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'folders': 'list[MailServerFolder]'
    }

    attribute_map = {
        'folders': 'Folders'
    }

    def __init__(self, folders=None):
        """
        ListFoldersResponse - a model defined in Swagger
        """

        self._folders = None
        self.discriminator = None

        if folders is not None:
          self.folders = folders

    @property
    def folders(self):
        """
        Gets the folders of this ListFoldersResponse.
        Gets or sets array of mailbox folders.

        :return: The folders of this ListFoldersResponse.
        :rtype: list[MailServerFolder]
        """
        return self._folders

    @folders.setter
    def folders(self, folders):
        """
        Sets the folders of this ListFoldersResponse.
        Gets or sets array of mailbox folders.

        :param folders: The folders of this ListFoldersResponse.
        :type: list[MailServerFolder]
        """

        self._folders = folders

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ListFoldersResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
