# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.storage_api import StorageApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_disc_usage(self):
        """Test case for get_disc_usage

        Get disc usage  # noqa: E501
        """
        pass

    def test_get_file_versions(self):
        """Test case for get_file_versions

        Get file versions  # noqa: E501
        """
        pass

    def test_object_exists(self):
        """Test case for object_exists

        Check if file or folder exists  # noqa: E501
        """
        pass

    def test_storage_exists(self):
        """Test case for storage_exists

        Check if storage exists  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
