# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.contact_api import ContactApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.contact_api.ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_contact_attachment(self):
        """Test case for add_contact_attachment

        Add attachment to contact document  # noqa: E501
        """
        pass

    def test_create_contact(self):
        """Test case for create_contact

        Create contact document  # noqa: E501
        """
        pass

    def test_delete_contact_property(self):
        """Test case for delete_contact_property

        Delete property from indexed property list  # noqa: E501
        """
        pass

    def test_get_contact_attachment(self):
        """Test case for get_contact_attachment

        Get attachment file by name  # noqa: E501
        """
        pass

    def test_get_contact_list(self):
        """Test case for get_contact_list

        Get contact list from storage folder  # noqa: E501
        """
        pass

    def test_get_contact_properties(self):
        """Test case for get_contact_properties

        Get contact document properties  # noqa: E501
        """
        pass

    def test_update_contact_properties(self):
        """Test case for update_contact_properties

        Update contact document properties  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
