# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.folder_api import FolderApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestFolderApi(unittest.TestCase):
    """FolderApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.folder_api.FolderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_folder(self):
        """Test case for copy_folder

        Copy folder  # noqa: E501
        """
        pass

    def test_create_folder(self):
        """Test case for create_folder

        Create the folder  # noqa: E501
        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        Delete folder  # noqa: E501
        """
        pass

    def test_get_files_list(self):
        """Test case for get_files_list

        Get all files and folders within a folder  # noqa: E501
        """
        pass

    def test_move_folder(self):
        """Test case for move_folder

        Move folder  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
