# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.calendar_api import CalendarApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestCalendarApi(unittest.TestCase):
    """CalendarApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.calendar_api.CalendarApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_calendar_attachment(self):
        """Test case for add_calendar_attachment

        Adds an attachment to iCalendar file  # noqa: E501
        """
        pass

    def test_create_calendar(self):
        """Test case for create_calendar

        Create calendar file  # noqa: E501
        """
        pass

    def test_delete_calendar_property(self):
        """Test case for delete_calendar_property

        Deletes indexed property by index and name. To delete Reminder attachment, use path ReminderAttachment/{ReminderIndex}/{AttachmentIndex}  # noqa: E501
        """
        pass

    def test_get_calendar(self):
        """Test case for get_calendar

        Get calendar file properties  # noqa: E501
        """
        pass

    def test_get_calendar_attachment(self):
        """Test case for get_calendar_attachment

        Get iCalendar document attachment by name  # noqa: E501
        """
        pass

    def test_get_calendar_list(self):
        """Test case for get_calendar_list

        Get iCalendar files list in folder on storage  # noqa: E501
        """
        pass

    def test_update_calendar_properties(self):
        """Test case for update_calendar_properties

        Update calendar file properties  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
