# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.file_api import FileApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.file_api.FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_file(self):
        """Test case for copy_file

        Copy file  # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete file  # noqa: E501
        """
        pass

    def test_download_file(self):
        """Test case for download_file

        Download file  # noqa: E501
        """
        pass

    def test_move_file(self):
        """Test case for move_file

        Move file  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Upload file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
