# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.email_api import EmailApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.email_api.EmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_email_attachment(self):
        """Test case for add_email_attachment

        Adds an attachment to Email document  # noqa: E501
        """
        pass

    def test_create_email(self):
        """Test case for create_email

        Create an email document  # noqa: E501
        """
        pass

    def test_get_email(self):
        """Test case for get_email

        Get email document  # noqa: E501
        """
        pass

    def test_get_email_attachment(self):
        """Test case for get_email_attachment

        Get email attachment by name  # noqa: E501
        """
        pass

    def test_get_email_property(self):
        """Test case for get_email_property

        Get an email document property by its name  # noqa: E501
        """
        pass

    def test_set_email_property(self):
        """Test case for set_email_property

        Set email document property value  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
