# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.models.append_email_account_base_request import AppendEmailAccountBaseRequest  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestAppendEmailAccountBaseRequest(unittest.TestCase):
    """AppendEmailAccountBaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppendEmailAccountBaseRequest(self):
        """Test AppendEmailAccountBaseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsposeEmailCloudSdk.models.append_email_account_base_request.AppendEmailAccountBaseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
