# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.mapi_api import MapiApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestMapiApi(unittest.TestCase):
    """MapiApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.mapi_api.MapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_mapi_attachment(self):
        """Test case for add_mapi_attachment

        Add attachment to document  # noqa: E501
        """
        pass

    def test_create_mapi(self):
        """Test case for create_mapi

        Create new document  # noqa: E501
        """
        pass

    def test_delete_mapi_attachment(self):
        """Test case for delete_mapi_attachment

        Remove attachment from document  # noqa: E501
        """
        pass

    def test_delete_mapi_properties(self):
        """Test case for delete_mapi_properties

        Delete document properties  # noqa: E501
        """
        pass

    def test_get_mapi_attachment(self):
        """Test case for get_mapi_attachment

        Get document attachment as file stream  # noqa: E501
        """
        pass

    def test_get_mapi_attachments(self):
        """Test case for get_mapi_attachments

        Get document attachment list  # noqa: E501
        """
        pass

    def test_get_mapi_list(self):
        """Test case for get_mapi_list

        Get document list from storage folder  # noqa: E501
        """
        pass

    def test_get_mapi_properties(self):
        """Test case for get_mapi_properties

        Get document properties  # noqa: E501
        """
        pass

    def test_update_mapi_properties(self):
        """Test case for update_mapi_properties

        Update document properties  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
