# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.api.email_client_api import EmailClientApi  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestEmailClientApi(unittest.TestCase):
    """EmailClientApi unit test stubs"""

    def setUp(self):
        self.api = AsposeEmailCloudSdk.api.email_client_api.EmailClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_append_email_message(self):
        """Test case for append_email_message

        Adds an email from *.eml file to specified folder in email account  # noqa: E501
        """
        pass

    def test_append_mime_message(self):
        """Test case for append_mime_message

        Adds an email from MIME to specified folder in email account  # noqa: E501
        """
        pass

    def test_create_email_folder(self):
        """Test case for create_email_folder

        Create new folder in email account  # noqa: E501
        """
        pass

    def test_delete_email_folder(self):
        """Test case for delete_email_folder

        Delete a folder in email account  # noqa: E501
        """
        pass

    def test_delete_email_message(self):
        """Test case for delete_email_message

        Delete message from email account by id  # noqa: E501
        """
        pass

    def test_fetch_email_message(self):
        """Test case for fetch_email_message

        Fetch message mime from email account  # noqa: E501
        """
        pass

    def test_list_email_folders(self):
        """Test case for list_email_folders

        Get folders list in email account  # noqa: E501
        """
        pass

    def test_list_email_messages(self):
        """Test case for list_email_messages

        Get messages from folder, filtered by query  # noqa: E501
        """
        pass

    def test_save_mail_account(self):
        """Test case for save_mail_account

        Create email account file (*.account) with login/password authentication  # noqa: E501
        """
        pass

    def test_save_mail_o_auth_account(self):
        """Test case for save_mail_o_auth_account

        Create email account file (*.account) with OAuth  # noqa: E501
        """
        pass

    def test_send_email(self):
        """Test case for send_email

        Send an email from *.eml file located on storage  # noqa: E501
        """
        pass

    def test_send_email_mime(self):
        """Test case for send_email_mime

        Send an email specified by MIME in request  # noqa: E501
        """
        pass

    def test_set_email_read_flag(self):
        """Test case for set_email_read_flag

        Sets \"Message is read\" flag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
