# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.models.delete_folder_base_request import DeleteFolderBaseRequest  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestDeleteFolderBaseRequest(unittest.TestCase):
    """DeleteFolderBaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteFolderBaseRequest(self):
        """Test DeleteFolderBaseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsposeEmailCloudSdk.models.delete_folder_base_request.DeleteFolderBaseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
