# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.models.add_attachment_request import AddAttachmentRequest  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestAddAttachmentRequest(unittest.TestCase):
    """AddAttachmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddAttachmentRequest(self):
        """Test AddAttachmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsposeEmailCloudSdk.models.add_attachment_request.AddAttachmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
