# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.models.list_response_of_string import ListResponseOfString  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestListResponseOfString(unittest.TestCase):
    """ListResponseOfString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListResponseOfString(self):
        """Test ListResponseOfString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsposeEmailCloudSdk.models.list_response_of_string.ListResponseOfString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
