# coding: utf-8

"""
    Aspose.Email Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import AsposeEmailCloudSdk
from AsposeEmailCloudSdk.models.save_o_auth_email_account_request import SaveOAuthEmailAccountRequest  # noqa: E501
from AsposeEmailCloudSdk.rest import ApiException


class TestSaveOAuthEmailAccountRequest(unittest.TestCase):
    """SaveOAuthEmailAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveOAuthEmailAccountRequest(self):
        """Test SaveOAuthEmailAccountRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsposeEmailCloudSdk.models.save_o_auth_email_account_request.SaveOAuthEmailAccountRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
