name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r sdk/requirements.txt
        python -m pip install -r tests/requirements.txt
    - name: Test with pytest
      env:
        clientId: ${{secrets.appSidProd}}
        clientSecret: ${{secrets.appKeyProd}}
        apiBaseUrl: "https://api.aspose.cloud"
      run: |
        python -m pytest --verbose --color=yes -m pipeline tests
